sudo: required
services:
  - docker

before_install:
  - docker build -t heinefjeld/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true heinefjeld/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react"
  env: "Dockerreact.env"
  bucket_name: "elasticbeanstalk-eu-north-1-432571206514"
  bucket_path: "docker-react"
  on:
    branch: master

language: generic